version: '2'

services:
  app:
    image: 'docker.io/best_insurance/api:latest'
    container_name: app
    depends_on:
      db:
        condition: service_started
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5005
      - BPL_DEBUG_SUSPEND=false

  db:
    image: 'postgres:14.5-alpine'
    container_name: db
    ports:
      - '55432:5432'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
